armory/documentation

_install_guide/dns_and_ssl.md

one liner cert gen and reorder instructions

one liner cert gen and reorder instructions

---

_install_guide/spinnaker-deploy-spinnaker.md

improve spinnaker-deploy-spinnaker bake stage docs
- Installation Guide subsection "Re-deploying Spinnaker" > "Spinnaker Deploy Spinnaker"

improve spinnaker-deploy-spinnaker bake stage docs

---

_install_guide/auth.md

fixed spelling mistake

---

_install_guide/auth.md

Merges https://github.com/Armory/documentation/pull/180
- github auth provider removed.

remove unused provider setting

---

_install_guide/authz.md

Service accounts

---

_install_guide/authz.md

small image fix

---

_install_guide/authz.md

GitHub fiat

---

_install_guide/authz.md

Updating documentation for new permissions model which has read/write groups

Updating to new permissions model [ENG-1103]

---

_release_notes/armoryspinnaker_v1.10.174.md

Release 1-10-174 ENG-1118

---

_assets/css/components/_posts.scss

Adds rule for margins on doubly nested ul or ol elements in post content.

Fix Doubly Nested Lists

---

_install_guide/auth.md

add google config, made other configs generic

---

_install_guide/auth.md

update generic oauth with empty fields

---

_install_guide/authz.md

add authz more info

---

_install_guide/config_repo.md

add warning on using deb-s3

---

_user_guides/kubernetes-v2.md

Documentation for the Kubernetes V2 Provider

K8v2 guide

---

_user_guides/baking-images.md
_user_guides/kubernetes-v2.md

Adding some chroot documentation

adding chroot documentation and fixing kube v2

---

.coafile

simple coafile to use with coala for spelling/grammer

adding coa file to help with grammar and spelling

---

_user_guides/kubernetes-v2.md

Two in one paragraph! Impresive!

Fix multiple misspellings of Kubernetes

---

_install_guide/application_pipeline.md

Fixed broken link in application_pipeline.md

---

_release_notes/armoryspinnaker_v1.11.0.md

1.11.0 Release notes

---

_install_guide/auth.md

Updating auth to import the CA

---

_install_guide/dinghy.md

fix indentation

---

_admin_guides/advanced_configuration.md
_install_guide/auth.md

Add cluster timeout

---

_admin_guides/advanced_configuration.md

advanced config title fix

---

_admin_guides/rosco.md

- Updated spacing in documentation that was reported to affect the execution of the yml file
- Wicked mean breakdancing

Updated documentation spacing, which was reported to cause issues.

---

_install_guide/dinghy.md

added link to spinnaker docs for creating service account

---

_release_notes/armoryspinnaker_v1.12.5.md

v1.12.5 release

---

_admin_guides/troubleshooting.md

updating docs for disablign security

---

_install_guide/dinghy.md

updated wording for customers who dont have configurator installed

---

_admin_guides/rosco.md

fixing spacing issues with rosco example

---

README.md
_admin_guides/rosco.md
_includes/components/youtubePlayer.html
_user_guides/video-tutorials.md

Added a video tutorials page for the documentation
- Ben M. breakdancing, and Ben C. still writes Markdown like a pro.

Video Tutorials

---

_install_guide/dinghy.md

fixed couple typos

---

Gemfile
_config.yml
_user_guides/dinghy.md

add redirect from old pipeline templates page to dinghy

---

_user_guides/dinghy.md

what works in dev doesnt work in prod!

---

_admin_guides/advanced_configuration.md
_install_guide/logging.md

Adds documentation for the monitoring container.

Datadog monitoring

---

_user_guides/dinghy.md

This should be merged with https://github.com/armory-io/dinghy/pull/40

Update dinghy docs to use vars

---

_install_guide/auth.md

Fixing this stuff up.  it was super jacked

fixing auth documentation

---

_admin_guides/integration_test_pipelines.md

Integration tests

---

_install_guide/jenkins.md

fixing the url that is used in the docs.

fixing jenkins url

---

_user_guides/working-with-jenkins.md

updating docs

---

_install_guide/dinghy.md
_user_guides/dinghy.md

updating dinghy docs

---

_admin_guides/notifications.md

updated docs to reflect email notifications

---

_user_guides/video-tutorials.md

I fixed a typo found `Pipline` in the [Video Tutorials page](https://docs.armory.io/user-guides/video-tutorials/#video-tutorials)
- No worry, Small changes.

fix: Pipline to Pipeline

---

_admin_guides/notifications.md
_admin_guides/troubleshooting.md

Updated docs to warn of the perils of Flushall 

---

_user_guides/kubernetes-v2.md

Fix documentation on enabling Kubernetes V2

fix(v2-early): fix config for v2 early access

---

_overview/overview-of-spinnaker.md

updated image

---

Gemfile.lock
_install_guide/gettings_started.md
_install_guide/install.md

Added a link to a form asking for details on K8s install

added k8s link

---

_install_guide/install.md

document uninstall command for armory spinnaker

document uninstall

---

_install_guide/dns_and_ssl.md

make it clearer on what's going on with the variables.

clear, meaningful variables

---

_includes/base/header.html
_includes/components/articles-list.html
_release_notes/armoryspinnaker_v1.12.5.md

They'll still show up if you go directly to the link

feat(article-list) ability to hide posts from the list

---

_release_notes/armoryspinnaker_v1.13.4.md
_release_notes/armoryspinnaker_v1.13.7.md

feat(release-notes) add v1.13.x release notes

---

_install_guide/oneclick.md

one-click docs

---

_install_guide/oneclick.md

better explanation of template fields

---

_admin_guides/configure_kubernetes.md

add configuration for enabling the use of ECR repositories

feat(ecr): add aws ecr config

---

_release_notes/armoryspinnaker_v1.13.7.md

<kbd>![](https://cl.ly/2E2v0y3T0u04/Screen%20Shot%202018-07-11%20at%2014.29.57.png)</kbd>

feat(1.13.7) known issue with ssh_private_ip in packer templates

---

_config.yml
_includes/base/header.html
_install_guide/install.md
_overview/overview-of-spinnaker.md

updated install page and front page

Drodio 0716

---

_includes/base/footer.html
_install_guide/install.md

Updated demo link and footer

---

_admin_guides/kayenta.md
_admin_guides/notifications.md
_user_guides/kayenta.md

Contains information for configuring New Relic in Kayenta, but not for best practices to configure the pipeline.

New Relic in Kayenta

---

_release_notes/armoryspinnaker_v1.14.192.md

feat(v1.14.192) add known issue on baking this version

---

_spinnaker/install.md

Used these directions to get installer working in Docker.

Put Docker instructions back.

---

_spinnaker/install.md

Adds some "Before You Start" sections to help users know what they will expect to need before proceeding.

ENG-2443 Update Docs w/ Requirements

---

_spinnaker/configure_ingress.md

Also removed bit about certs, because we don't actually use them in the end.

Change leftover "paul"s to "demo".

---

_spinnaker/authorization.md

(doc/auth) Document "Propagate Authentication"

---

Jenkinsfile

Change upstreamProject name to match the path on Jenkins

Update upstream project name

---

_spinnaker/configure_kayenta.md

...since we can't configure our New Relic support via Halyard yet.

Add example YAML for New Relic config

---

_spinnaker/configure_ingress.md

adds documentation on how to enable sticky sessions for Gate

docs(sticky): add docs on enabling sticky sessions

---

_spinnaker/terraform_integration.md

updates the docs to reflect installation with halyard.

docs(terraform): update to reflect halyard

---

_spinnaker_install_admin_guides/okta.md

docs(otka): removing incorrect port from a command

---

_spinnaker/terraform_integration.md

One day I'm gonna learn to use git properly, but today is not that day.

docs(update): Add Terraformer Bitbucket documentation

---

_install_guide/install.md
_spinnaker/install.md

feat(site): Redirect old install page to relevant page.

---

_admin_guides/kayenta.md
_spinnaker_user_guides/kayenta.md

`The was an error is` is actually what shows up... 
https://spinnakerteam.slack.com/archives/C2W6RE0N4/p1559268046016300

fix(docs): Kayenta storage canary config

---

_overview/overview-of-spinnaker.md

🎫 https://trello.com/c/TcE4T4sn/58-check-semrush-on-issues

site(seo): Fix mixed content HTTPS issue on docs homepage.

---

_spinnaker/terraform_integration.md

Don't merge this until 2.4.1 gets released.

docs(terraform): Add Terraformer "Output" documentation

---

_spinnaker/terraform_integration.md

DO NOT MERGE UNTIL 2.4.2 is released.

feat(terraformer): document support for terraform version selection

---

_spinnaker/terraform_integration.md

DO NOT MERGE UNTIL >= 2.5.2 IS RELEASED

feat(terraformer): document base64 artifacts and custom plugins

---

_spinnaker_install_admin_guides/vault-configuration.md

Conflicts with Liquid markup otherwise

fix(docs):  Need to escape the go syntax

---

_spinnaker_install_admin_guides/secrets-s3.md
_spinnaker_install_admin_guides/secrets-vault.md
_spinnaker_install_admin_guides/secrets.md

Also adds the rewording from the OSS docs code review.

fix(secrets): replace namespace param with path

---

_overview/overview-of-spinnaker.md

Changed the size of the image so that it doesn't cause the first paragraph to have an indent. Also removed some trailing whitespaces.

docs(formatting): Remove first paragraph indent

---

_spinnaker/using_dinghy.md

* Includes example of application permissions configuration.
* Cleaned up section headers (consistency)

task(dinghy):  Document outer config block

---

_spinnaker_install_admin_guides/install-on-aws.md

docs(bug): Add missing redirect

---

_spinnaker_install_admin_guides/halyard-gitops.md

New GitOps guide including sample scripts for running halyard.

doc(gitops): Updated GitOps guide

---

_includes/base/head.html

Swaps out the javascript snippet from Intercom to Drift
https://trello.com/c/fCYFLBTN/153-swap-intercom-to-drift-on-both-blog-docs-kb

feat(site): Swaps intercom for drift

---

_spinnaker/operator-config.md
_spinnaker/operator.md

Copy of descriptions in the wiki of spinnaker operator repo

doc(operator): Description of SpinnakerServiceCRD and operator configmap

---

_spinnaker/exposing_spinnaker.md

I added the HTTP/HTTPS info and renamed the file as requested

docs(https): add http/https info

---

_spinnaker/operator-config.md

Implementation for file references changed.

doc(operator): Updating file keys of operator ConfigMap

---

_spinnaker_install_admin_guides/install-on-gke.md

fix(docs): FIx documentation typos.

---

_admin_guides/integration_test_pipelines.md

refact(integration_test_pipeline): this is not a legacy doc
refact(integration_test_pipeline): remove random whitespace

refact(integration_test_pipeline): readability and dedeprecation

---

_spinnaker/using_dinghy.md

Added undocumented necessary parameters to instructions under Create a Dinghyfile from an Existing Pipeline

Docs(Fix) Added previously missing required step for creating dinghyfile from preexsisting pipeline. 

---

_spinnaker/using_dinghy.md

docs(fix): Add missing step for creating pipeline from pre-existing pipeline

---

_overview/overview-of-spinnaker.md

Signed-off-by: Aimee Ukasick <aimeeu.opensource@gmail.com>

docs(fix): fix typo in Deployment Strategies/Canary (#697)

---

_spinnaker/policy_engine.md

Fix the markdown formatting so things get rendered properly
https://share.getcloudapp.com/BluEbqAn

docs(policyengine): fix markdown formatting

---

_spinnaker/install.md

I have added some content to start promoting Minnaker as an easier way to get Spinnaker up and running.  I'd ❤️ to get some additional 👀 on this.

docs(documentation): Add content for Minnaker

---

_spinnaker/install_dinghy.md

fix(docs): Small edits

---

_spinnaker/account_management_api.md

Add account management early release docs to docs site. We were sharing a copy that was in Paper. More customers are asking for it, so moving to public docs.

docs(accountmgmt): add account mgmt docs

---

_spinnaker/Armory-Spinnaker-Quickstart-1.md

docs(fix): spelling errors

---

_spinnaker/Armory-Spinnaker-Quickstart-1.md

docs(quickstart): fixed structure errors in document from swarm

---

_spinnaker/operator-config.md
_spinnaker/operator.md

Updated old references and notes.

chore(doc): Operator documentation updates

---

_spinnaker/install.md

So two questions: 
(1) Is it ok to mount the PVC to the spinnaker home directory directly? instead of .hal 
(2) Does everything else look ok with the halyard.yml

fix(install): Making halyard.yml use a StatefulSet instead of a Deployment

---

_spinnaker_user_guides/video-tutorials.md

docs(fix): Typo 'pipline'

---

_spinnaker_install_admin_guides/install-on-aws.md

docs(install/aws): Remove placeholder text

---

_spinnaker_install_admin_guides/install-on-aws.md

workaround for our PR title checker. Merged to an Armory branch and now to master.

docs(install/aws): fix toc

---

_spinnaker_install_admin_guides/install-on-gke.md

Google was incorrectly spelled.

fix(docs): Typo fix

---

_spinnaker_install_admin_guides/install-on-aks.md
_spinnaker_install_admin_guides/install-on-aws.md
_spinnaker_install_admin_guides/install-on-gke.md

This is the ready to publish version of this document for https://armory.atlassian.net/browse/DOC-104

docs(install): Install on Azure Kubernetes Service

---

_spinnaker_install_admin_guides/install-on-aks.md
_spinnaker_install_admin_guides/install-on-aws.md
_spinnaker_install_admin_guides/install-on-gke.md

spelling changes caught during blog post review

fix(docs): Spelling fixes

---

_spinnaker/terraform_integration.md

- Cleanup based on discussion in standup
- Removed Gate proxy stuff for logs that's no longer needed

docs(terraformer): clean up logs and system defined

---

_spinnaker/terraform_integration.md

fixed the section but not the title last time 🤦‍♂

docs(tf): fix section title

---

_includes/base/header.html

I couldn't get spacing between the first nav item and the button 🤷‍♂ , but it works. Good enough for now.
https://s.armory.io/NQuZKbvE

docs(support): add support button by request of andrew

---

_spinnaker/policy_engine.md

add `--require-policy-label` as discussed in slack

docs(policy): add OPA configmap label

---

_release_notes/armoryspinnaker_v2.18.0.md

Policy Engine known issue from SUPPORT-1093 for 2.18.0

docs(pe): add known issue 

---

_spinnaker/operator.md

add how to migrate from halyard to operator documentation.

feat(docs/migrate-from-halyard): add how to migrate from halyard

---

_spinnaker/operator.md

Added missing config for operator container to pick up vault configuration.

doc(operator): Fix for custom halyard config volumes

---

_spinnaker_install_admin_guides/add-aws-account-iam.md
_spinnaker_install_admin_guides/add-aws-account.md
_spinnaker_install_admin_guides/add-kubernetes-account.md
_spinnaker_install_admin_guides/api-endpoint.md
_spinnaker_install_admin_guides/aws-dr.md
_spinnaker_install_admin_guides/clouddriver-sql.md
_spinnaker_install_admin_guides/configure-halyard.md
_spinnaker_install_admin_guides/dns-and-ssl.md
_spinnaker_install_admin_guides/docker.md
_spinnaker_install_admin_guides/ecr-registry.md
_spinnaker_install_admin_guides/fiat-create-permissions.md
_spinnaker_install_admin_guides/github.md
_spinnaker_install_admin_guides/install-on-k8s.md
_spinnaker_install_admin_guides/jenkins.md
_spinnaker_install_admin_guides/okta.md
_spinnaker_install_admin_guides/orca-sql.md
_spinnaker_install_admin_guides/rate-limit.md
_spinnaker_install_admin_guides/s3.md
_spinnaker_install_admin_guides/secrets-gcs.md
_spinnaker_install_admin_guides/secrets-kubernetes.md
_spinnaker_install_admin_guides/secrets-s3.md
_spinnaker_install_admin_guides/secrets-vault.md
_spinnaker_install_admin_guides/secrets.md
_spinnaker_install_admin_guides/services-mtls.md
_spinnaker_install_admin_guides/services-tls.md
_spinnaker_install_admin_guides/slack-notifications.md
_spinnaker_install_admin_guides/sumologic-dashboard.md
_spinnaker_install_admin_guides/vault-configuration.md

Merge after https://github.com/armory/documentation/pull/816

doc(operator): Added operator configs to admin guides

---

_spinnaker/pacrd-crd-docs.md
_spinnaker/pacrd.md

Before Merge:
- https://github.com/armory-io/pacrd/pull/16

feat(pacrd): add crd documentation

---

_spinnaker_install_admin_guides/install-on-gke.md

Jira: DOCS-73
Note: I already updated the file in docs360.

docs(fix): Fix ingress controller name in Set up DNS.

---

_spinnaker/pacrd.md

I realized in my last PR I only bumped the patch version, but it really should have been a minor version because of the backwards incompatible changes, soz.

feat(pacrd): bump release of pacrd

---

_spinnaker_install_admin_guides/install-on-gke-operator.md

Based on Michael Brown's [document](https://paper.dropbox.com/doc/Operator-to-Deploy-Spinnaker-to-GKE--AyS6CQVHy57I4PYlm_g4b8BMAg-lFX2seaoBk5YnzT94BPNj).
Jira: [ENG-5164](https://armory.atlassian.net/browse/ENG-5164)

docs(gce): Add Install Spinnaker on GCE Using Operator

---

_spinnaker/Armory-Spinnaker-Quickstart-1.md
_spinnaker/Armory-Spinnaker-Quickstart-2.md
_spinnaker/Armory-Spinnaker-Quickstart-3.md
_spinnaker/exposing_spinnaker.md
_spinnaker/install_dinghy.md
_spinnaker/operator.md
_spinnaker/terraform_integration.md
_spinnaker/using_dinghy.md
_spinnaker_install_admin_guides/add-kubernetes-account.md
_spinnaker_install_admin_guides/air-gapped.md
_spinnaker_install_admin_guides/install-on-aks.md
_spinnaker_install_admin_guides/install-on-aws.md
_spinnaker_install_admin_guides/install-on-k8s-notes.md
_spinnaker_install_admin_guides/install-on-k8s.md
_spinnaker_install_admin_guides/secrets-vault.md

First chunk of files w/ the whitespace issue resolved.

docs(space): fix the spacing

---

_spinnaker_install_admin_guides/install-on-gke-operator.md

This PR consists of updates to the install on GKE with operator document based on user and customer feedback from the field. The order is also changed so this is below the main gke install doc.

fix(docs): install gke with operator updates

---

_spinnaker/account_management_api.md

Hide account management API by request of Chris

docs(api): hide account management api doc

---

_spinnaker/configure_kayenta.md
_spinnaker_install_admin_guides/add-aws-account.md
_spinnaker_install_admin_guides/api-endpoint.md
_spinnaker_install_admin_guides/github.md
_spinnaker_install_admin_guides/secrets-vault.md
_spinnaker_install_admin_guides/vault-configuration.md

Follow up to https://github.com/armory/documentation/pull/863
This PR resolves the whitespace issue for the rest of our top 25 most visited pages.

docs(fix): white spaces

---

_spinnaker_install_admin_guides/secrets-vault.md

<kbd>![image](https://user-images.githubusercontent.com/3469532/81348349-c68ca900-9072-11ea-8c40-fbf1bb455f43.png)
</kbd>

feat(secrets): improve readability and cleanup

---

_spinnaker/install_dinghy.md
_spinnaker/using_dinghy.md

+ Added conditionals example in Dinghy docs
+ Fixed typos
+ Added reference to arm-cli

fix(dinghy): Added conditional example in Dinghy docs

---

_spinnaker_user_guides/deploying.md

docs(aws): add detail to ebs block

---

_spinnaker/install_dinghy.md
_spinnaker/terraform-enable-integration.md

Added Redis section to Dinghy and Terraformer since the config
is not the same as the Java bases microservices

docs(redis): Added Redis section to Dinghy and Terraformer

---

_spinnaker/terraform-enable-integration.md

chow is not a command, fixing to chown

fix(docs): typo in enabling secrets for tf

---

assets/react/static/js/main.af139ce3.js

Rendered: https://s.armory.io/DOuQ7z9r
EULA goes to https://www.armory.io/terms-of-service/
Terms goes to https://www.armory.io/terms-and-conditions/

docs(footer): add eula and fix t&c

---

_release_notes/armoryspinnaker_v2.19.8.md

Missed adding the line to this version.

docs(release-notes): add missing line

---

_spinnaker_install_admin_guides/vault-configuration.md

Update the links to the debug container for doc-131

docs(vault): link fix for doc-131

---

_spinnaker/aws-container-marketplace.md

Error handling, fix api version, etc.

fix(marketplace): Some fixes
