armory/documentation

_install_guide/auth.md
jekyll does some weird stuff with indenting inside a list with code blocks.
=> add whitespace before codeblock, jekyll renders weird indents

_install_guide/config_repo.md, _install_guide/gettings_started.md, _install_guide/initial_setup.md
- add docs on configurator
- add docs on secrets management
companion PRs:
-  https://github.com/Armory/spinnaker-config-deb/pull/17 (example how to use secret files)
- https://github.com/armory-io/armoryspinnaker/pull/256 (allow bin/start to run env/resolved-env)
- https://github.com/armory-io/armoryspinnaker/pull/258 (source `*-secrets.yml` for docker compose)
=> add docs on configurator and secrets management

_user_guides/barometer.md, _user_guides/find-images.md, _user_guides/sla.md
Adds documentation for the new configurable SLA feature.  Page is currently hidden as the feature's not generally available yet.
=> ENG-1290 SLA docs

_install_guide/auth.md
the oauth configuration allows you to filter users by userInfo
attributes. this can be useful to limit authn to members of a particular
domain.
i also removed references to Google Groups because OAuth doesn't utilize
that feature for Authentication. Fiat utilizes it for Authorization.
- None
- [ X ] some level of documentation, links:
=> add userInfoRequirements callout in the oauth conf

_user_guides/kayenta.md
Example shows how to deploy the canary cluster, run the analysis, and then
clean up (on fail) or promote (on success) the canary afterwards.
=> Define a "production-like" Kayenta pipeline.

_install_guide/auth.md
the ldap docs were missing the `AUTH_ENABLED` instructions.
=> fix(authn): update ldap docs

_release_notes/armoryspinnaker_v1.13.7.md
Spinnaker user is now  inside a running docker instance. This could cause some issues with reading files, a solution is provided above
=> feat(v1.13.7) add known issue for spinnaker user ENG-1977

_release_notes/armoryspinnaker_v1.13.7.md
The real docs for https://github.com/armory/documentation/pull/301
In chrome, the service worker tries to fetch a file from /armory/config, but the nginx rules redirect it. Chrome provents this and throws an error
=> fix(1.13.7) the service worker prevents redirects

_install_guide/logging.md
it looks like we added `spinnaker-monitoring.yml` in a recent release to
overriding it requires `-local`
=> fix(monitoring): update docs

_install_guide/adding_accounts.md
- Followed https://docs.armory.io/install-guide/adding_accounts/#adding-additional-aws-accounts
- After configuration per documentation, 403s in clouddriver were preventing healthy boot.
- 403s were ManagingAccount:role/SpinnakerInstanceProfile failing to assume role for ManagedAccount:role:SpinnakerManagedProfile
- Found and followed CloudDriver documentation that elaborates on additional IAM Role/Policy changes that resolved this issue.
- Docs:  https://github.com/spinnaker/clouddriver/tree/9a77e558fcf63d71c1ff0b4219fedbbbc4e6f6de/clouddriver-aws#configuring-the-managing-account
=> Updated install_guide/adding_accounts for multiple AWS accounts to clarify AssumeRole nuance.

_spinnaker/install.md
Add instructions for using kubectl to port forward to deck & gate after
using the Docker container to do the install.
=> Remove port mapping on Docker command

_spinnaker/configure_kayenta.md
Mostly copying the existing docs for configuring canary configs (not including
the stage definition yet).  Includes reference to OSS configuration docs for
using hal to configure/enable kayenta.
=> (doc/kayenta) Initial documentation for Kayenta

_spinnaker/install.md
The `.armory` directory is no longer needed. All writes happen to `~/.hal`
=> Removed docs for ~/.armory

_spinnaker/armory_halyard.md, _spinnaker/configure_ingress.md
Does not include SSL support yet, but has end-to-end working solution for non-SSL.
=> ENG-2502: Document setting up AWS LB for Spinnaker

_spinnaker/install.md
Updated https://docs.armory.io/spinnaker/install/ with references to standard Halyard docs (https://www.spinnaker.io/reference/halyard/).
=> ENG-2713: Added references to standard Halyard documentation

_data/versions.yml, _spinnaker/install.md, bin/build
Each time a build of these docs is triggered in Jenkins, the build script will retrieve the latest docker tag of halyard-armory from the last successful build on master.
=> ENG-2863: Automatically update armory halyard docker tag on each build

README.md, _includes/components/regex_vs_wildcard.md, _spinnaker_install_admin_guides/docker.md, _spinnaker_install_admin_guides/ecr-registry.md, _spinnaker_install_admin_guides/github.md, _spinnaker_install_admin_guides/jenkins.md, _spinnaker_install_admin_guides/s3.md, _spinnaker_user_guides/docker.md, _spinnaker_user_guides/github.md, _spinnaker_user_guides/s3.md, _spinnaker_user_guides/webhooks.md, _spinnaker_user_guides/working-with-jenkins.md
Quick-start guides for configuring things like Jenkins masters, Github and S3 artifact accounts, etc.
Configuration in Admin Guides, Usage in User Guides (which have links to the configuration guides to make sure people know what needs to be set up first)
Also added a reusable callout/note about the difference between a "regular expression" and a "wildcard" (not often a problem, but trips up enough people it seemed warranted to call out)
=> chore(docs):  Add updated walkthroughs for some features

_spinnaker/armory_halyard.md, _spinnaker/install_dinghy.md
In Halyard 1.6.3+, you can configure Dinghy to send notifications to
Slack when a Dinghyfile has been processed (success/failure).
=> feat(dinghy):  Add commands for configuring Slack

_spinnaker/terraform_integration.md
Added:
* Clarification about GitHub user name not needed when token is used
* Github API url format for `github/file` artifacts
=> docs(terraformer): Added format of github file artifacts url.

_spinnaker_install_admin_guides/install-on-eks.md, _spinnaker_install_admin_guides/install-on-gke.md
the core kubernetes documentation moved the documentation and corresponding yaml files to a new location making our docs out of date.  could I get some :eyes: on this?
=> fix(docs): core kubernetes mapping for ingress

_spinnaker_install_admin_guides/api-endpoint.md
It looks like some of the references to the service were missed when they were copied from the Deck section. I've corrected this by swapping Deck/Gate to make it easier to follow.
=> Fixes copypasta problems deck=>gate in api-endpoint docs

_spinnaker/install.md
Did some small cleanup and added the links to AWS and GKS docs
=> docs(install): add links to aws and gke installs

_spinnaker_install_admin_guides/install-on-gke.md
2 typos on "export KUBCONFIG=kubeconfig-gke"
kubernetes namespace started as "spinnaker-system" but became "spinnaker" at the ingress setup
=> export typos and namespace consistency

_overview/overview-of-spinnaker.md
Fix 'intance' typo in Deployment Strategies section, Canary bullet point.
Looks like my editor removed a trailing space at the end of the first paragraph in the Safety and Speed section.
Signed-off-by: Aimee Ukasick <aimeeu.opensource@gmail.com>
=> Fix typo in Deployment Strategies/Canary

_spinnaker/policy_engine.md
- remove bash from the codeblocks. It caused random words to be pink
- change the ConfigMap to be 2 ConfigMaps like the OPA docs https://www.openpolicyagent.org/docs/latest/deployments/#kubernetes
- put in the right hal command cause hal config deploy should be hal deploy apply
- add toc
=> docs(policyEngine): update configMaps and cleanup

_install_guide/application_pipeline.md, _spinnaker/terraform_integration.md, _spinnaker/using_dinghy.md, _spinnaker_user_guides/application-pipeline.md
* Updating links to proper URL from localhost:4000
* Spelling error on 'Bitbucket' in Terraform documentation
Closes https://github.com/armory/documentation/issues/713.
=> docs(fix): Minor documentation fixes

_spinnaker/policy_engine.md
Discussed this with Beth because customers are asking about the required Spinnaker version. These aren't the actual minimum versions. We just know that the policy engine works on this version for sure because it was the GA version when policy engine was announced as "GA."
=> docs(version): add recommended Spinnaker versions

_includes/base/header.html
This PR adds asynchronous Google Custom Search Engine functionality to the left navigation bar.  The reader types a search term in the box and either clicks the `search` icon or hits enter on the keyboard. Results from Google CSE are displayed in a pop up modal window within the browser window.
1.  Created Google custom search engine at https://cse.google.com/  for docs.armory.io; google account: aimee.ukasick@armory.io
1. Customized look at feel using CSE control panel
1. Inserted script link and google search div in _includes/base/header.html
Preview on my Netlify account:   https://deploy-preview-6--brave-panini-8017d6.netlify.com/
=> docs(search): Add google custom search 

_spinnaker_install_admin_guides/install-on-aws.md, _spinnaker_install_admin_guides/install-on-gke.md
This note was added to the OSS doc back in December (by me). It reminds users to wait until containers are running before trying to connect to the application. This is because the hal deploy completes but the application it likely still not running. The OSS pull request was: https://github.com/spinnaker/spinnaker.github.io/pull/1609
=> docs(troubleshooting): Add note about waiting until containers are running before expecting to connect

_includes/base/header.html, _install_guide/install.md, _spinnaker/install.md
Remove the mentions of the demo environment. We're directing prospects to Minnaker instead.
=> docs(demo): remove link to demo env

_spinnaker_install_admin_guides/install-on-gke.md
docs: Update to NGINX instructions on install guide
Updated to reflect that the NGINX ingress controller only works on K8s version 1.14 and higher and to only perform  step if cluster doesn't have one already. Also referenced the nginx docs in case of running version older than 1.14
=> fix(docs): Update install-on-gke.md

_spinnaker/Armory-Spinnaker-Quickstart-1.md, _spinnaker/Armory-Spinnaker-Quickstart-2.md, _spinnaker/Armory-Spinnaker-Quickstart-3.md
fixed spacing problem with json that kept it from being cut and pasted into AWS console. Added clearer text on how to get FQDN for nginx test page for EKS deployment. Added clarity over updating account ID in json. Removed a cut/paste error from a previous AWS guide that referenced a name that was not present in this guide. **NOTE: You may want to make sure that json formats correctly with the tabs removed when the doc page is rendered. I did not test that.
=> fix(docs): bugs in AWS quickstart

_spinnaker/Armory-Spinnaker-Quickstart-2.md
This just makes this block of code look like the other bash commands to be executed. Basic formatting only.
=> fix(docs): change from code to bash to match other formatting

_spinnaker_install_admin_guides/jenkins.md
- Clarify that the reader must create a user-based API token in Jenkins.
- Reorder paragraphs
- Use brackets for placeholders in commands
=> docs(fix): clarify Jenkins password

_spinnaker/operator.md
From @echenarmory:
in https://docs.armory.io/spinnaker/operator/ under Install Spinnaker with Operator and Kustomize, point 2 should have:
```
kubectl create ns <spinnaker-namespace> 
kustomize build deploy/spinnaker/kustomize | kubectl -n <spinnaker-namespace> apply -f - 
```
the docs say “kubectl build …” which is not a real option
=> docs(fix): fix incorrect command

_spinnaker_install_admin_guides/install-on-k8s.md
Added instructions for how to install Spinnaker using the Operator to the existing `Installing Spinnaker in Kubernetes` guide (https://docs.armory.io/spinnaker-install-admin-guides/install-on-k8s/)
=> doc(install): Added operator section to kubernetes install guide

_overview/your-first-application.md
k8s v1 provider is deprecated. This was a requirement that came from that.
https://www.spinnaker.io/reference/providers/kubernetes-v2/#no-restrictive-naming-policies
=> docs(fix): remove naming requirement. requirement was for k8s v1

_spinnaker/install.md
Ofter discussion with Kevin Woo, we believe that the macos installation of halyard isn't the recommended path forward and hence, should be removed from the documentation. This pull request is open for discussion but represents what the end "halyard installation" documentation would look like without the macos section.
=> docs(hal): removed macos from installation guide for halyard

_operator_reference/operator-config.md
Moved this file and forgot to add as part of PR #820 
Spinnaker Operator Reference left nav should look like:
https://s.armory.io/xQuWdNZ1
=> docs(fix): Move operator-config to operator_reference folder

_spinnaker_user_guides/docker.md, _spinnaker_user_guides/kayenta.md, _spinnaker_user_guides/kustomize-manifests.md, _spinnaker_user_guides/s3.md, _spinnaker_user_guides/working-with-jenkins.md
Please merge after https://github.com/armory/documentation/pull/816
This PR adds operator specific configs to docs in `User Guides` section.
=> doc(operator): Added operator configs to user guides

_spinnaker_install_admin_guides/generating-certificates.md, _spinnaker_install_admin_guides/services-tls.md
- add subjAlternateNames (useful for Spinnaker 1.19+, okHttp change)
=> fix(tls/options): Fix options for TLS secrets

_spinnaker/operator.md
Remove the line about cloning the repo. It pointed to a private repo
=> docs(fix): remove private repo link

_spinnaker/policy_engine.md
2.19 adds runtime validation for Policy Engine, which requires a config in clouddriver. I followed the same pattern as the existing operator config for it but haven't had a chance to verify.
=> docs(policy): update operator section to include config for runtime validation

_operator_reference/security.md, _operator_reference/spinnakerservice.yml
According to the code ui ssl is different from api ssl, it follows [ApacheSsl](https://github.com/spinnaker/halyard/blob/master/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/ApacheSsl.java) model
=> docs(security): Fix Ui ssl config and parameters on Halconfig

_release_notes/armoryspinnaker_v2.19.4.md, _release_notes/armoryspinnaker_v2.19.5.md, _release_notes/armoryspinnaker_v2.19.6.md, _release_notes/armoryspinnaker_v2.19.7.md
=> feat(releases): adds v2.19.7

_spinnaker_install_admin_guides/dynamic_accounts.md
This document explains how to use the OSS external configuration feature with vault to dynamically load kubernetes accounts. It takes the information that is in the OSS docs and makes it usable.
=> docs(dynamic-accounts): initial creation

_operator_reference/armory.md, _operator_reference/artifact.md, _operator_reference/canary.md, _operator_reference/ci.md, _operator_reference/metricstores.md, _operator_reference/notification.md, _operator_reference/persistent-storage.md, _operator_reference/providers.md, _operator_reference/pubsub.md, _operator_reference/repository.md, _operator_reference/security.md, _operator_reference/webhook.md
Indicate which parameters support encrypted values with "Supports encrypted value."
Indicate which file parameters require a local file with "File needs to be present on the machine running Spinnaker." (pulled from the Java source code)
Indicate which file parameters support an encrypted file with "Supports encrypted file."
=> docs(operator-ref): Indicate which parameters support encrypted

_spinnaker/policy_engine.md
Only the settings.js profile requires a pipe; other ones do not.
Also, remove placeholders in OPA installation, which probably cause more confusion than anything else.
=> fix(docs): Profiles don't require a pipe

_spinnaker_user_guides/deploying.md
I added description of additional settings to `Additional Launch Block Devices`.
The page is https://docs.armory.io/spinnaker-user-guides/deploying/#additional-launch-block-devices.
=> docs(aws): add detail to ebs block

_spinnaker_install_admin_guides/architecture.md
Running my first PR against Armory Docs to test out and document the process in thorough detail. There was a mini typo in Architecture.md.
=> docs(Architecture.md): Changed Terrafomer typo to Terraformer

_spinnaker_install_admin_guides/okta.md
correct the missing syntax for accessing secrets needed in the operator section. Instructions are invalid without this fix.
=> docs(operator): incorrect operator secret syntax for bob-141

_release_notes/armoryspinnaker_v2.19.4.md, _release_notes/armoryspinnaker_v2.19.5.md, _release_notes/armoryspinnaker_v2.19.6.md, _release_notes/armoryspinnaker_v2.19.7.md, _release_notes/armoryspinnaker_v2.19.8.md
Added to all 2.19.x release notes about Table Renaming breaking change,  where table gets renamed, does not get reverted if you need to go back to 2.18.x.
=> docs(release_notes): MySQL Table Renaming Breaking Change

_spinnaker/using_dinghy.md, _spinnaker_install_admin_guides/okta.md
Add link to dinghy example templates (doc-99), and add missing hal deploy apply to okta example (doc-103).
=> docs(fixes): dinghy template examples and okta halyard fix
